package app.posato.control.core

import kotlinx.serialization.json.JsonElement

private const val EXIT_FAILED = 1
private const val EXIT_USAGE = 2
private const val EXIT_PRECONDITION = 3
private const val EXIT_NOT_FOUND = 4
private const val EXIT_BUILD = 5
private const val EXIT_UNSUPPORTED = 6

enum class ErrorCode(
    val exitCode: Int
) {
    USAGE(EXIT_USAGE),
    TCC_ACCESSIBILITY_DENIED(EXIT_PRECONDITION),
    TCC_SCREEN_RECORDING_DENIED(EXIT_PRECONDITION),
    NO_BOOTED_SIMULATOR(EXIT_PRECONDITION),
    NO_CONNECTED_DEVICE(EXIT_PRECONDITION),
    DEVICE_AUTOMATION_LOCKED(EXIT_PRECONDITION),
    VM_UNAVAILABLE(EXIT_PRECONDITION),
    DISK_SPACE_LOW(EXIT_PRECONDITION),
    ICLOUD_KEYCHAIN_PAUSED(EXIT_PRECONDITION),
    WORKSPACE_LINKED(EXIT_PRECONDITION),
    DESKTOP_HOST_REFUSED(EXIT_PRECONDITION),
    DEVELOPMENT_TEAM_MISSING(EXIT_PRECONDITION),
    APP_NOT_STAGED(EXIT_PRECONDITION),
    PACKAGE_OUTDATED(EXIT_PRECONDITION),
    TOOL_OUTDATED(EXIT_PRECONDITION),
    PRECONDITION_NOT_MET(EXIT_PRECONDITION),
    APP_NOT_INSTALLED(EXIT_PRECONDITION),
    APP_NOT_RUNNING(EXIT_PRECONDITION),
    PROCESS_NOT_ALLOWED(EXIT_PRECONDITION),
    PROCESS_NOT_INSPECTABLE(EXIT_PRECONDITION),
    DESKTOP_WINDOW_UNAVAILABLE(EXIT_NOT_FOUND),
    ALREADY_RUNNING(EXIT_PRECONDITION),
    ALREADY_EXISTS(EXIT_PRECONDITION),
    REFUSED_WITHOUT_CONFIRMATION(EXIT_PRECONDITION),
    ELEMENT_NOT_FOUND(EXIT_NOT_FOUND),
    ELEMENT_AMBIGUOUS(EXIT_NOT_FOUND),
    WAIT_TIMEOUT(EXIT_NOT_FOUND),
    ASSERTION_FAILED(EXIT_NOT_FOUND),
    SCENARIO_INVALID(EXIT_NOT_FOUND),
    BUILD_FAILED(EXIT_BUILD),
    INSTALL_FAILED(EXIT_BUILD),
    DRIVER_FAILED(EXIT_FAILED),
    COMMAND_FAILED(EXIT_FAILED),
    UNSUPPORTED_ON_TARGET(EXIT_UNSUPPORTED),
}

/** A failed command; [result] is what it had done before it failed, which its envelope reports beside the error. */
class ControlException(
    val code: ErrorCode,
    message: String,
    val hint: String? = null,
    cause: Throwable? = null,
    val result: JsonElement? = null,
) : RuntimeException(message, cause)
