package app.posato.control.core

private const val EXIT_FAILED = 1
private const val EXIT_USAGE = 2
private const val EXIT_PRECONDITION = 3
private const val EXIT_NOT_FOUND = 4
private const val EXIT_BUILD = 5
private const val EXIT_UNSUPPORTED = 6

enum class ErrorCode(
    val exitCode: Int
) {
    USAGE(EXIT_USAGE),
    TCC_ACCESSIBILITY_DENIED(EXIT_PRECONDITION),
    TCC_SCREEN_RECORDING_DENIED(EXIT_PRECONDITION),
    NO_BOOTED_SIMULATOR(EXIT_PRECONDITION),
    NO_CONNECTED_DEVICE(EXIT_PRECONDITION),
    DEVELOPMENT_TEAM_MISSING(EXIT_PRECONDITION),
    APP_NOT_STAGED(EXIT_PRECONDITION),
    APP_NOT_INSTALLED(EXIT_PRECONDITION),
    APP_NOT_RUNNING(EXIT_PRECONDITION),
    ALREADY_RUNNING(EXIT_PRECONDITION),
    REFUSED_WITHOUT_CONFIRMATION(EXIT_PRECONDITION),
    ELEMENT_NOT_FOUND(EXIT_NOT_FOUND),
    ELEMENT_AMBIGUOUS(EXIT_NOT_FOUND),
    WAIT_TIMEOUT(EXIT_NOT_FOUND),
    ASSERTION_FAILED(EXIT_NOT_FOUND),
    SCENARIO_INVALID(EXIT_NOT_FOUND),
    BUILD_FAILED(EXIT_BUILD),
    INSTALL_FAILED(EXIT_BUILD),
    DRIVER_FAILED(EXIT_FAILED),
    COMMAND_FAILED(EXIT_FAILED),
    UNSUPPORTED_ON_TARGET(EXIT_UNSUPPORTED),
}

class ControlException(
    val code: ErrorCode,
    message: String,
    val hint: String? = null,
    cause: Throwable? = null,
) : RuntimeException(message, cause)
